# Generated by Django 5.2.8 on 2025-12-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('natural_language_input', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Vendors'), ('review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_days', models.IntegerField(default=30)),
                ('payment_terms', models.TextField(blank=True)),
                ('warranty', models.TextField(blank=True)),
                ('requirements', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(default='General', max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=300)),
                ('email_body', models.TextField()),
                ('raw_response', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_data', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_delivery_days', models.IntegerField(blank=True, null=True)),
                ('proposed_terms', models.TextField(blank=True)),
                ('warranty_offered', models.TextField(blank=True)),
                ('compliance_score', models.FloatField(default=0.0)),
                ('is_parsed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='rfp.rfp')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfp.vendor')),
            ],
            options={
                'ordering': ['-compliance_score', 'total_price'],
                'unique_together': {('rfp', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_recommendation', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('proposals', models.ManyToManyField(to='rfp.proposal')),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='rfp.rfp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFPSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_subject', models.CharField(max_length=300)),
                ('email_body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_error', models.TextField(blank=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfp.rfp')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfp.vendor')),
            ],
            options={
                'unique_together': {('rfp', 'vendor')},
            },
        ),
        migrations.AddField(
            model_name='rfp',
            name='vendors',
            field=models.ManyToManyField(through='rfp.RFPSendLog', to='rfp.vendor'),
        ),
    ]
