# Generated by Django 5.2.8 on 2025-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='natural_language_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='vendors',
            field=models.ManyToManyField(related_name='rfps', through='rfp.RFPSendLog', to='rfp.vendor'),
        ),
    ]
