# Generated by Django 5.2.8 on 2025-12-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0002_alter_rfp_natural_language_input_alter_rfp_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='rfp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='rfp.rfp'),
        ),
    ]
